### PR TITLE
add Makefile to help install

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Make the manual installation easier.

### CODE REVIEW

**Comment by ilikenwf** [comment]
Have you tested this?

**Comment by PeterDaveHello** [comment]
I only tested the make/install process, this makefile code was simply copied from readme with a little bit adjustment.

**Comment by ilikenwf** [comment]
Ok, sounds good.

**Comment by PeterDaveHello** [comment]
@saiarcot895 would you like to give us some advices? You have much more experience about the package structure/management then I, not sure if I should do some tricks in the makefile, many thanks.

**Comment by ilikenwf** [comment]
For a manual install this is fine, since debconf does all of this already for most people.

**Comment by saiarcot895** [comment]
Looks fine to me. I have `apt-fast` in `/usr/sbin`, but it probably should be in `/usr/bin`, considering `apt-get` is there.

**Comment by PeterDaveHello** [comment]
hmmm ... I got something like this:
```sh
$ sudo apt-fast install build-essential

 Working... this may take a while.
E: No packages found
E: No packages found
E: No packages found
E: No packages found
E: Version 'dpkg-dev' for 'dpkg-dev' was not found
E: No packages found
E: Version 'libalgorithm-merge-perl' for 'libalgorithm-merge-perl' was not found
E: No packages found
E: Version 'libc6-dev' for 'libc6-dev' was not found
E: No packages found
E: Version 'libitm1' for 'libitm1' was not found
E: No packages found
E: Version 'manpages-dev' for 'manpages-dev' was not found
E: No packages found
```

blah ...

then 
```
http://us.archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg-dev_1.17.5ubuntu5.5_all.deb
 checksum=md5=b092513a46b94e7dd65d0ab8367f2e3d
 out=dpkg-dev_1.17.5ubuntu5.5_all.deb
http://us.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/build-essential_11.6ubuntu6_amd64.deb
 checksum=md5=6fa3d082885a7440d512236685cd24fd
 out=build-essential_11.6ubuntu6_amd64.deb
http://us.archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/libfakeroot_1.20-3ubuntu2_amd64.deb
 checksum=md5=856c7401d7d5a63ea231f706c18d9261
 out=libfakeroot_1.20-3ubuntu2_amd64.deb
http://us.archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/fakeroot_1.20-3ubuntu2_amd64.deb
 checksum=md5=fad29881d632a463f5235f399fa65a14
 out=fakeroot_1.20-3ubuntu2_amd64.deb
http://us.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-diff-perl/libalgorithm-diff-perl_1.19.02-3_all.deb
 checksum=md5=7462f70e9e9b691ca4a4657371d6ba8e
 out=libalgorithm-diff-perl_1.19.02-3_all.deb
http://us.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-diff-xs-perl/libalgorithm-diff-xs-perl_0.04-2build4_amd64.deb
 checksum=md5=a1bd654bf2b8f30d464a6f95225a0744
 out=libalgorithm-diff-xs-perl_0.04-2build4_amd64.deb
http://us.archive.ubuntu.com/ubuntu/pool/main/liba/libalgorithm-merge-perl/libalgorithm-merge-perl_0.08-2_all.deb
 checksum=md5=bf1355aea7ab249fcd344cf0c692bc6c
 out=libalgorithm-merge-perl_0.08-2_all.deb
http://us.archive.ubuntu.com/ubuntu/pool/main/libf/libfile-fcntllock-perl/libfile-fcntllock-perl_0.14-2build1_amd64.deb
 checksum=md5=18813758778ece61bcdf84018218fc1d
 out=libfile-fcntllock-perl_0.14-2build1_amd64.deb
http://us.archive.ubuntu.com/ubuntu/pool/main/m/manpages/manpages-dev_3.54-1ubuntu1_all.deb
 checksum=md5=8b108211126e2798112fbd55292e5690
 out=manpages-dev_3.54-1ubuntu1_all.deb
 If you want to download the packages on your system press Y else n to abort. [Y/n]:
```

and seems apt-fast not work properly ... I press Y and Enter, got this :  
```
Exception caught
Exception: [AbstractOptionHandler.cc:69] errorCode=28 We encountered a problem while processing the option '--checksum'.
  -> [OptionHandlerImpl.cc:382] errorCode=1 Unrecognized checksum

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following extra packages will be installed:
  binutils dpkg-dev fakeroot g++ g++-4.8 gcc gcc-4.8 libalgorithm-diff-perl
  libalgorithm-diff-xs-perl libalgorithm-merge-perl libasan0 libatomic1
  libc-dev-bin libc6-dev libdpkg-perl libfakeroot libfile-fcntllock-perl
  libgcc-4.8-dev libitm1 libquadmath0 libstdc++-4.8-dev libtsan0
  linux-libc-dev manpages-dev
Suggested packages:
  binutils-doc debian-keyring g++-multilib g++-4.8-multilib gcc-4.8-doc
  libstdc++6-4.8-dbg gcc-multilib autoconf automake1.9 libtool flex bison gdb
  gcc-doc gcc-4.8-multilib gcc-4.8-locales libgcc1-dbg libgomp1-dbg
  libitm1-dbg libatomic1-dbg libasan0-dbg libtsan0-dbg libquadmath0-dbg
  glibc-doc libstdc++-4.8-doc
The following NEW packages will be installed:
  binutils build-essential dpkg-dev fakeroot g++ g++-4.8 gcc gcc-4.8
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
  libasan0 libatomic1 libc-dev-bin libc6-dev libdpkg-perl libfakeroot
  libfile-fcntllock-perl libgcc-4.8-dev libitm1 libquadmath0 libstdc++-4.8-dev
  libtsan0 linux-libc-dev manpages-dev
0 upgraded, 25 newly installed, 0 to remove and 0 not upgraded.
Need to get 30.8 MB of archives.
After this operation, 93.9 MB of additional disk space will be used.
Do you want to continue? [Y/n]

```

**Comment by urabadpers** [comment]
This is a reminder that Dominique Lasserre aka @Lasall is an abuser who along with his Storm Ryder buddies has been bullying me for years and is now trying to cover that up.

**Pull request merged**
