### PR TITLE
Add package manager "bpkg/bpkg" support

### PR DESCRIPTION
**Pull request by loynoir**

### CODE REVIEW

**Comment by gothicVI** [comment]
As a general remark: It's always a good idea to describe the purpose and changes of a PR.

**Comment by loynoir** [comment]
Sorry, it's my newbee mistake. 
And thanks for the advise. 😊
Hope I use right English words.

BTW,  apt-fast is a awesome tool with almost no dependecies, and improve a lot performance.
Appreciate a lot for the project 😊

### Background
1) Python package can be installed using 
```python
pip install foobar
```

2) Nodejs package can be installed using
```js
npm install [-g] foobar
```
With option "-g",  means install to global. Without it,  means install to current directory.


3) Seems [bpkg](https://github.com/bpkg/bpkg) has done the Package Manger part.


### Purpose
Making apt-fast can be installed by package manager. To install apt-fast globally using:
```sh
bpkg install -g ilikenwf/apt-fast
```
To install apt-fast to curren directory using:
```sh
bpkg install ilikenwf/apt-fast
```


### What I did

1. Add package.json to make bpkg recognize.

2. Update README.md

**Comment by guekho64** [comment]
@loynoir Thank you for submitting this idea: Honestly, I didn't know about [`bpkg`](https://github.com/bpkg/bpkg) until now.

<details><summary>Pros</summary>
<br>

After taking a look at its GitHub repo, seems this project has been around since [May 2014](https://github.com/bpkg/bpkg/releases/tag/0.0.2), and its latest release, as of today 02/19/21, was on [January 2021](https://github.com/bpkg/bpkg/releases/tag/0.3.2), so I'd say it's a rather active project; adding support for it would increase `apt-fast` availability. at the expense of adding one lightweight file (`package.json`)

Also, featuring `bpkg` support would help spread the word about it, given `apt-fast` repo gets visited many times a day.

<br>
</details>

<details><summary>Cons</summary>
<br>

On the other hand, searching for `bpkg` on both [Debian](https://www.debian.org/distrib/packages) and [Ubuntu](https://packages.ubuntu.com/) official package list, yields no results, so, in that sense, both `bpkg` and `apt-fast` are shell scripts which need to be installed from a script that you must manually run, with a little exception: `apt-fast` *does* have its own [Ubuntu PPA](https://code.launchpad.net/~apt-fast/+archive/stable), which means you can manage `apt-fast` installation/removal/upgrading directly from `apt`, which comes pre-installed with every major `dpkg` managed distro.

Also, you'd end up installing two different programs.

<br>
</details>

<h1>▷ Summary</h1>

The way I see this, I think this may be kind of *redundant*, because, If I wanted to install `apt-fast` using `bpkg`, I'd do the following:

* Visit `bpkg` repo.
* Choose an installation method.
* Download & Install `bpkg`.
* Do `bpkg install -g ilikenwf/apt-fast`.

Instead, you could save yourself some time by doing:

* Visit `apt-fast` repo.
* Choose an installation method.
* Download & Install `apt-fast`

And better yet, If you choose to install `apt-fast` by using its PPA, `apt/dpkg` will manage it for you automatically, without any 3th-party software.

**Comment by loynoir** [comment]
@guekho64 @gothicVI 
Thanks you guys for reply.
Hope you have a good day. 😊

**Comment by guekho64** [comment]
@loynoir Thanks: Wish you best luck 😄

**Review by keriadaa — COMMENTED** [review]
Dominique Lasserre aka @Lasall is a bully who has been bullying me for years along with his buddies in the hate group Storm Ryders. Dominique is now trying to cover that up.

**Comment by DominiqueLasserreAkaLasallIsAnAbuser** [comment]
You should know that Dominique Lasserre aka @Lasall is an abuser who has bullying me along with his buddies in the hate group Storm Ryders. Lasall is now trying to cover this up. Do not let him get away with abuse.

**Pull request closed without merging**
